### ISSUE TITLE
OCM component section should have examples of a complete ocm spec

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-spec#34]
**What would you like to be added**:

https://github.com/open-component-model/ocm-spec/blob/main/doc/specification/elements/README.md#components

This is missing a complete spec of how multiple components would look like in a single file.

**Why is this needed**:

**Comment by In-Ko** [comment]
How is this requirement related to https://github.com/open-component-model/ocm-website/issues/26 ? What is the difference ? Do you suggest to also introduce an example which shows usage of multiple components, like an aggregated component ?

**Comment by Skarlso** [comment]
Oh cool. Thanks. I missed that one. :) Yeah that looks good to me.
