### ISSUE TITLE
Add "Transport" / "Transport Format" to the OCM Specification

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm-spec#4]
**Description**
One of the features / use cases which is enabled with the OCM is the ability to transport the full closure of a software component from one Component Repository (e.g. an OCI Registry, an S3 bucket, a file system) to another Component Repository.
It needs to be described in full detail how this works, especially how the OCM spec and the OCM tools enable the transportability of software components. This means the OCM specifications needs dedicated chapters for the Transportation Feature overall, and one for the "Transport Format" (aka CTF = Common Transport Format) (For the CTF, there is already a first WiP document here: https://github.com/gardener/ocm-spec/blob/main/doc/proposal/in-progress/06-tranport-format.md.)

**Done Criteria**
- [x] A new chapter covering the topic of "Transportability of Software Components" is available in the OCM Specification
- [x] A new chapter specifying the "Common Transport Format" is added to the OCM Specification

**Comment by mandelsoft** [comment]
#33
