### ISSUE TITLE
Eliminate duplicate JSON Schema, link to the one in OCM Repo

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm-spec#51]
**Description**
There are currently two JSON Schema for the Component Descriptor, one in this repo (OCM-SPEC) and one in Repo "OCM". We should not have two schemas, but only one.
We decided to keep the one in the OCM-Repo, as it is required there also for technical reasons (due to the library and CLI being also in that Repo), and get rid of the JSON schema in the OCM-SPEC repo.

1. Delete this: https://github.com/open-component-model/ocm-spec/tree/main/doc/specification/formats/compdesc (and if required link to the ones mentioned under (2), for people who have this URL bookmarked already)
2. Keep this and use it for now as the one-and-only JSON Schema place: https://github.com/open-component-model/ocm/tree/main/docs/formats/compdesc

**Comment by jensh007** [comment]
accidentally closed.

**Comment by jensh007** [comment]
#57 added
