### ISSUE TITLE
RepoCtx specification incomplete

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm-spec#58]
**What would you like to be added**:
The repoCtx in a component-descriptor looks like this:
```
    - type: ociRegistry
      baseUrl: eu.gcr.io
      subPath: sap-cp-k8s-ocm-gcp-eu30-dev/dev/d058463/microblog
```

The subPath is not mentioned in the spec. Why do we need two fields `baseUrl` and `subPath`?

**Why is this needed**:
Specification is not complete.

**Comment by jensh007** [comment]
See also: https://github.com/open-component-model/ocm/issues/388

**Comment by morri-son** [comment]
@jensh007 isn't this related to https://github.com/open-component-model/ocm/issues/388 and maybe possible to be done in on issue?
