### ISSUE TITLE
Specify more precisely definition of uniquenees of identity/names in a component

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm-spec#64]
> The name of the element. In most of the cases the name should be chosen to be unique in the context of the list of elements. It basically also expresses the meaning or purpose of the element in the context of the component version. 

It must be more precisely defined that a identity MUST be uniqe and that an extraIdentity is required if a name is not unique.

**Comment by morri-son** [comment]
done: https://github.com/open-component-model/ocm-spec/blob/f68b746949815b25930c7a50c83077bb7015e2ab/doc/01-model/03-elements-sub.md?plain=1#L44
