### ISSUE TITLE
gitHub access artifact content is provided as gnu-zipped tar archive

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm-spec#72]
[Appendix B](https://github.com/open-component-model/ocm-spec/blob/main/doc/appendix/B/gitHub.md) states: 

> Provided blobs use the following media type for: application/x-tgz

This means that we can store entire git repositories in a component version. When does this happen and how do we prevent huge content blobs? Needs clarification (only for sources? are sources ever transported?)

**Comment by robertwol** [comment]
@mandelsoft could you assist with confirmation on this topic?

**Comment by morri-son** [comment]
Hi @jensh007 , I guess this is similar to --copy-resources during a transfer. Here we can use --copy-sources to add the sources specified via commit/ref to the component version. And yes, in principle this can become quite large, but is not different from large images for example. I don't really see a relevant use case where one would do this, though...

**Comment by jensh007** [comment]
Agreed. Closing this.
