### ISSUE TITLE
Add one complete Component Descriptor example to the OCM Spec

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm-spec#8]
**Description**
The OCM specification needs one concrete example of a component descriptor (in YAML), covering all required and all optional fields, including comments for each field explaining the meaning, whether they are optional or mandatory and so on.

**Done Criteria**
- [ ] A complete example exists in the ocm-spec repo, covering all elements a CD could possibly have.

**Comment by ikhandamirov** [comment]
#31 merged, topic can be closed as confirmed by @jensh007
